# Use ubuntu as the base image
FROM ubuntu

# Install curl
RUN apt update && apt install -y curl

# Set a default command to print "Hello from my custom image!"
CMD ["echo","Hello from my custom image!"]

# For ENTRYPOINT example
ENTRYPOINT ["echo","hello"]
